import { Dish } from "./dish-object";
import { Category } from "./category";
import { Cuisine } from "./cuisine";
import { DishType } from "./type";


export const DISHES: Dish[] = [
    {
        // id: 0,
        name: 'Carbonara',
        cuisine: 'Italian',
        type: 'Meat',
        category: 'Dinner',
        ingredients: 'pasta, eggs, cheese, cured pork',
        selectedNumber: 0,
        maxNumber: 25,
        price: 37,
        priceUSD: 37,
        priceEUR: 32.87,
        description: 'Carbonara is an Italian pasta dish from Rome made with eggs, hard cheese, cured pork, and black pepper. The dish arrived at its modern form, with its current name, in the middle of the 20th century.',
        img: ['https://images.unsplash.com/photo-1612874742237-6526221588e3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80'],
        rate: 4,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 1,
        name: 'French Crepes',
        cuisine: 'French',
        type: 'Sweet',
        category: 'Breakfast',
        ingredients: 'flour, milk,eggs,cream cheese, chocolate sauce, seasonal fruits',
        selectedNumber: 0,
        maxNumber: 30,
        price: 34,
        priceUSD: 34,
        priceEUR: 30.2,
        description: 'Crepe is a type of very thin pancake. Crêpes originated in Brittany (a region in the west of France) during the 13th century, but are now consumed around the world.',
        img: ['https://images.unsplash.com/photo-1584278860047-22db9ff82bed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'],
        rate: 4,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 2,
        name: 'Ratatouille',
        cuisine: 'French',
        type: 'Vegetarian',
        category: 'Dinner',
        ingredients: 'tomatoes, zucchini,eggplant',
        selectedNumber: 0,
        maxNumber: 10,
        price: 45,
        priceUSD: 45,
        priceEUR: 39.97,
        description: 'Ratatouille is a French Provençal dish of stewed vegetables, originating in Nice, and sometimes referred to as ratatouille niçoise',
        img: ['https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1070&q=80'],
        rate: 5,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 3,
        name: 'Sushi uramaki roll',
        cuisine: 'Japanese',
        type: 'Meat',
        category: 'Dinner',
        ingredients: 'rice, salmon, philadelphia,',
        selectedNumber: 0,
        maxNumber: 50,
        price: 50,
        priceUSD: 50,
        priceEUR: 44.41,
        description: 'Sushi is a traditional Japanese dish of prepared vinegared rice , usually with some sugar and salt, accompanied by a variety of ingredients , such as seafood, often raw, and vegetables. ',
        img: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'],
        rate: 5,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 4,
        name: 'Ramen',
        cuisine: 'Japanese',
        type: 'Meat',
        category: 'Dinner',
        ingredients: 'Chinese-style wheat noodles, meat, vegetables,',
        selectedNumber: 0,
        maxNumber: 10,
        price: 42,
        priceUSD: 42,
        priceEUR: 37.31,
        description: 'Ramen is a Japanese noodle soup. It consists of Chinese-style wheat noodles served in a meat or (occasionally) fish-based broth, often flavored with soy sauce or miso, and uses toppings such as sliced pork, nori (dried seaweed), menma, and scallions. ',
        img: ['https://images.unsplash.com/photo-1519077204685-ed90d0cc05b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032&q=80'],
        rate: 3,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 5,
        name: 'Neapolitan pizza',
        cuisine: 'Italian',
        type: 'Vegetarian',
        category: 'Dinner',
        ingredients: 'pizza dough, tomatoes, mozzarella , basil',
        selectedNumber: 0,
        maxNumber: 50,
        price: 39,
        priceUSD: 39,
        priceEUR: 34.64,
        description: ' Pizza Napoletana is a Traditional Speciality Guaranteed (TSG) product in the European Union and the United Kingdom, and the art of its making is included on UNESCO\'s list of intangible cultural heritage.',
        img: ['https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'],
        rate: 5,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 6,
        name: 'Hot-dog',
        cuisine: 'American',
        type: 'FastFood',
        category: 'Dinner',
        ingredients: 'sauasage, bun, toppings',
        selectedNumber: 0,
        maxNumber: 30,
        price: 26,
        priceUSD: 26,
        priceEUR: 23.1,
        description: 'Hot dog is a food consisting of a grilled or steamed sausage served in the slit of a partially sliced bun.The term hot dog can also refer to the sausage itself',
        img: ['https://images.unsplash.com/photo-1619740455993-9e612b1af08a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'],
        rate: 2,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 7,
        name: 'American cheesecake',
        cuisine: 'American',
        type: 'Sweet',
        category: 'Dessert',
        ingredients: 'cream cheese, sugar, pie crust, raspberry',
        selectedNumber: 0,
        maxNumber: 20,
        price: 28,
        priceUSD: 28,
        priceEUR: 24.87,
        description: 'New York–style cheesecake uses a cream cheese base, also incorporating heavy cream or sour cream. The typical New York cheesecake is rich and has a dense, smooth, and creamy consistency',
        img: ['https://images.unsplash.com/photo-1619985632461-f33748ef8f3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80'],
        rate: 3,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 8,
        name: 'Hamburger',
        cuisine: 'American',
        type: 'FastFood',
        category: 'Dinner',
        ingredients: 'ground meat, bun, lettuce,tomatoes',
        selectedNumber: 0,
        maxNumber: 20,
        price: 31,
        priceUSD: 31,
        priceEUR: 27.54,
        description: 'A hamburger is a food, typically considered a sandwich, consisting of one or more cooked patties—usually ground meat, typically beef—placed inside a sliced bread roll or bun. ',
        img: ['https://images.unsplash.com/photo-1550317138-10000687a72b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=920&q=80'],
        rate: 2,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 9,
        name: 'Tiramisu',
        cuisine: 'Italian',
        type: 'Sweet',
        category: 'Dessert',
        ingredients: 'savoiardi, egg yolks, mascarpone, cocoa, coffee',
        selectedNumber: 0,
        maxNumber: 30,
        price: 29,
        priceUSD: 29,
        priceEUR: 25.76,
        description: 'Tiramisu is a coffee-flavoured Italian dessert. It is made of ladyfingers (savoiardi) dipped in coffee, layered with a whipped mixture of eggs, sugar, and mascarpone cheese, flavoured with cocoa. ',
        img: ['https://images.unsplash.com/photo-1631206753348-db44968fd440?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80'],
        rate: 5,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 10,
        name: 'Scrambled eggs',
        cuisine: 'American',
        type: 'Vegetarian',
        category: 'Breakfast',
        ingredients: 'eggs',
        selectedNumber: 0,
        maxNumber: 50,
        price: 19,
        priceUSD: 19,
        priceEUR: 16.88,
        description: 'Scrambled eggs is a dish made from eggs (usually chicken eggs) stirred, whipped or beaten together while being gently heated, typically with salt, butter, oil and sometimes other ingredients ',
        img: ['https://images.unsplash.com/photo-1563690449029-d6e1b8d6003d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=866&q=80'],
        rate: 1,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
    {
        // id: 11,
        name: 'Teriyaki chicken',
        cuisine: 'Japanese',
        type: 'Meat',
        category: 'Dinner',
        ingredients: 'chicken, soy sauce, sugar',
        selectedNumber: 0,
        maxNumber: 10,
        price: 37,
        priceUSD: 37,
        priceEUR: 32.87,
        description: 'Teriyaki is a cooking technique used in Japanese cuisine in which foods are broiled or grilled with a glaze of soy sauce, mirin, and sugar.',
        img: ['https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'],
        rate: 3,
        rateNumber: 0,
        reviews: [],
        emailReview: [],
        emailRate: []
    },
]